### ISSUE TITLE
Version Mismatch issue for dll, WEM.Infrastructure.SecurityCore.dll

### ISSUE THREAD

**Issue by SudhaAmsoleInfy** [Infosys/Script-Control-Center#1]
While setting up Script Control Center using the release package, we are facing version mismatch issue for WEM.Infrastructure.SecurityCore.dll DLL

**Comment by abdulsajid95** [comment]
Check the available version of WEM.Infrastructure.SecurityCore.dll and update the versions (old and new) for the dll WEM.Infrastructure.SecurityCore.dll in the config files in which the dll is referred. The new version value should be updated as the available version of dll and old version should be a valid value.
