### ISSUE TITLE
Error Turn Windows Features On or Off for Script Centre

### ISSUE THREAD

**Issue by Prathamesh1197** [Infosys/Script-Control-Center#2]
While adding features using Turn Windows Features on or Off for Script Centre, we are getting error in VM's. PFA for reference. Any resolution for this?
<img width="579" alt="Screenshot 2022-12-28 173645" src="https://user-images.githubusercontent.com/121120224/209809790-7400b1ff-d1ee-4fdc-a718-08091ff4b102.png">

**Comment by sidrocks** [comment]
This could be an access issue. Pls go through this link for guidance with feature installation on a Windows system - https://support.microsoft.com/en-us/topic/when-trying-to-install-updates-from-windows-update-you-might-receive-updates-failed-there-were-problems-installing-some-updates-but-we-ll-try-again-later-with-errors-0x80073701-0x800f0988-e74b3505-f054-7f15-ec44-6ec0ab15f3e0

**Comment by Prathamesh1197** [comment]
We connected with ccd team and they have installed missing KB5001638, KB5021237 patches. Post that we were able to add features using Turn Windows Features on or Off for Script Centre in Akaash VM
