### ISSUE TITLE
Import/Export Utility

### ISSUE THREAD

**Issue by vivek0j** [Infosys/Script-Control-Center#4]
Hi, 

I need one help, where we can find the category id, company id for utility import/export purpose.

Regards,
Vivek

**Comment by abdulsajid95** [comment]
Hi Vivek,

You can skip the exporting steps. The scripts are exported and available in the folder ..\scripts\import.zip. You can continue with the steps to import the scripts.

Regards,
Sajid.

**Comment by vivek0j** [comment]
Hi Sajid, 

Getting error "Error occurring  while  uploading  scripts", while doing the import steps to import the scripts. Please guide me on this.

Regards,
Vivek

**Comment by vivek0j** [comment]
Hi Sajid,

Due to this, I'm not able to proceed with Administration Utility steps, as there I did not found Admin view, I only got blank screen.
Please help me on this.

Regards,
Vivek

**Comment by abdulsajid95** [comment]
Hi Vivek,

Make sure you have updated all configurations correctly like Database, server and LDAP domain in the config files below.
1. services > iapscriptstore > web.config
2. services > iapwemservices > web.config
3. utilities > ExportImportUtility > SCCSynchUtility.exe.config
4. Check if the file "Infosys.Lif.IISDoc.dll" is available at the location "C:\IAP\References\" and "C:\Infosys.IntegrationLib\References\"

Can you confirm which document you are using? Is it from the github source (use this document https://github.com/Infosys/Script-Control-Center/tree/main/Documents) or from the release files?

**Comment by vivek0j** [comment]
Hi Sajid,

I was following the same document. I have all the setup on E drive. So not for step 4 we didn't find IAP folder so manaually created one and pasted the requirement you suggested. Than Get another error with tag "IAP" reflecting "Couldnot load file or assembly infosys.JawaAccessBridge".

regards,
Vivek

**Comment by vivek0j** [comment]
Working now, Thank you
