### ISSUE TITLE
Script Control workbench issue

### ISSUE THREAD

**Issue by pooinfy5** [Infosys/Script-Control-Center#5]
Hi team,

We are facing issue while open the workbench application (msworkbench.shell) and it gives error.
We have atta
<img width="311" alt="script_control_workbench_issue" src="https://user-images.githubusercontent.com/125276020/218466358-abf8f9b4-ffa9-4bc4-8229-0593f7e2ea95.png">
ched the screenshot for the error.

**Comment by SudhaAmsoleInfy** [comment]
Hi Team,

the fix is available in the updated release, please get the latest release.

**Comment by pooinfy5** [comment]
Yes sure.Thank You
